version: '3'

services:
  codereview-tool-db-2:
    image: postgres:11.15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: codereview-tool-db
      POSTGRES_PASSWORD: codereview-tool-db
      POSTGRES_DB: codereview-tool-db-2
    ports:
      - 5432:5432
    volumes:
      - dbdata-2:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dbdata-2:
    driver: local
